CC = @gcc

FILES_C = main.c init.c input.c draw.c

P4TH = -I../!SDL2/include -L../!SDL2/lib
LIBS = -lmingw32 -lSDL2main -lSDL2

all:
	${CC} -o ../!Build/2D_Shooter-em_up.exe ${FILES_C} ${P4TH} ${LIBS}
